name: say-hello

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    if: github.event.pull_request.user.login != github.event.repository.owner.login
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "🎉 Hello @${{ github.event.pull_request.user.login }}, thanks for your first contribution!"
